import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// import Header from "@/components/header"; // Removed
import { Toaster } from "@/components/ui/sonner";
import { PlayerProvider } from "@/context/player-context";
import { MediaPlayer } from "@/components/media-player";
import { CollectionProvider } from "@/context/collection-context";
import { ThemeSynchronizer } from "@/components/theme-synchronizer";
import { ReaderSettingsProvider } from "@/context/use-reader-settings";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-foreground`}
      >
        <ReaderSettingsProvider>
          <PlayerProvider>
            <CollectionProvider>
              <ThemeSynchronizer />
              {children}
              <MediaPlayer />
              <Toaster />
            </CollectionProvider>
          </PlayerProvider>
        </ReaderSettingsProvider>
      </body>
    </html>
  );
}
